name: issue2notion issue sync

on:
  issues:
    types: [opened, reopened, closed, deleted]
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: issue2notion
    name: "Setup Node"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          always-auth: false
          repo-token: ${{ secrets.RATE_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: "Run issue sync to Notion"
        env:
          GITHUB_KEY: ${{ secrets.GITHUB_KEY }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
        run: node index.js