on:
  issues:
    types: [opened, reopened, closed, deleted]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run github issue notion sync"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: stup env
        run: npm install

      - name: "Create env file"
        run: /
          touch .env
          echo PERSONAL_GITHUB_ACCESS_KEY=${{ secrets.PERSONAL_GITHUB_ACCESS_KEY }} >> .env
          echo NOTION_KEY=${{ secrets.NOTION_KEY }} >> .env
          echo NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }} >> .env
          echo REPO_OWNER=${{ secrets.REPO_OWNER }} >> .env
          echo REPO_NAME=${{ secrets.REPO_NAME }} >> .env

      - name: "Start sync"
        run: node index.js